lazy initializes the singleton instances in the ICU4J and JDK text normalizers; fixes a defect in TextNormalizer; reduces the ICU4J dest buffer from 6x to 3x;
- fixes the flawed expansion measurement in ICU4JDestBufferWorstCaseExpansionTest pointed out by Fabian, resulting from starting the destination StringBuilder at zero capacity instead of 3x(source-length)
- TextNormalizer now correctly catches NoClassDefFoundError instead of Exception to detect when ICU4J is not available at runtime
- new parity test for the ICU4JTextNormalizer